"""add llm_call_log

Revision ID: 3e186ccdf00c
Revises: 56731a0e5d8d
Create Date: 2026-09-28 16:12:39.436771

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3e186ccdf00c"
down_revision: str | None = "56731a0e5d8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_call_log",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_call_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_call_log_project_id"),
            ["project_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_call_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_call_log_project_id"))

    op.drop_table("llm_call_log")
    # ### end Alembic commands ###
