"""add recycle_bin

Revision ID: 56731a0e5d8d
Revises: c4cd24f44c19
Create Date: 2026-09-28 15:23:10.829515

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "56731a0e5d8d"
down_revision: str | None = "c4cd24f44c19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recycle_bin",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("item_type", sa.String(length=32), nullable=False),
        sa.Column("enterprise_id", sa.String(length=32), nullable=True),
        sa.Column("ref_id", sa.String(length=32), nullable=False),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("purge_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["enterprise_id"], ["enterprise.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recycle_bin", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recycle_bin_enterprise_id"), ["enterprise_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recycle_bin", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recycle_bin_enterprise_id"))

    op.drop_table("recycle_bin")
    # ### end Alembic commands ###
