"""add recycle_bin_name_status_file_path

Revision ID: a1b2c3d4e5f6
Revises: 56731a0e5d8d
Create Date: 2026-09-29 10:00:00.000000

Task 21：回收站完整功能——新增名称/状态/文件路径列。
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "56731a0e5d8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recycle_bin", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=200), nullable=True))
        batch_op.add_column(
            sa.Column("status", sa.String(length=32), nullable=False, server_default="soft_deleted")
        )
        batch_op.add_column(sa.Column("original_name", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("file_path", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recycle_bin", schema=None) as batch_op:
        batch_op.drop_column("file_path")
        batch_op.drop_column("original_name")
        batch_op.drop_column("status")
        batch_op.drop_column("name")
    # ### end Alembic commands ###
